# Generated by Django 5.0.2 on 2024-03-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyabackend', '0002_dbpicture_delete_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbpicture',
            name='dbpicture_title',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instruction',
            name='instuction_title',
            field=models.TextField(default='Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text',
            field=models.TextField(default='instruction', max_length=500),
        ),
    ]
