# Generated by Django 5.0.2 on 2024-02-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyabackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbpicture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='Instruction_text',
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_text',
            field=models.TextField(default='instruction', max_length=300),
        ),
    ]
