# Generated by Django 5.0.2 on 2024-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyabackend', '0003_dbpicture_dbpicture_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruction',
            old_name='instuction_title',
            new_name='instruction_title',
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instruction_text',
            field=models.TextField(max_length=500),
        ),
    ]
