# Generated by Django 5.0.2 on 2024-03-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alyabackend', '0004_rename_instuction_title_instruction_instruction_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
